# Usign the Clean Blog theme

title: Homepage of Lihan Huang
author: Lihan Huang
email: lihan.huang@stonybrook.edu
description: homepage of lihan
baseurl: ""
url: "http://lihan960923.github.io/"
github_username:  lihan960923

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Welcome to Lihan's Homepage
gems:
  - jekyll-feed
  - jekyll-paginate
